# .release.toml
[workspace]
# Only allow releases from the main branch
allow-branch = ["main"]

# Perform version bumps, tagging, and changelog updates — but don't actually publish on dry runs
# This ensures cargo-release respects dependency ordering within the workspace
shared-version = true         # or true if you want one version for all crates
tag-prefix = ""               # avoids tags like crate-name-v0.1.0; optional
dependent-version = "upgrade" # automatically update dependent crate versions
consolidate-commits = true    # create a single release commit per crate


[release.mathengine-cli]
publish = false
tag = false
